List<String> sintomas = [
    "Coceira",
    "Erupção Cutânea",
    "Erupções Cutâneas Nodais",
    /*"Espirros Contínuos",
    "Tremores",
    "Calafrios",
    "Dor nas Articulações",
    "Dor de Estômago",
    "Acidez",
    "Úlceras na Língua",
    "Perda de Massa Muscular",
    "Vômito",
    "Queimação ao Urinar",
    "Manchas ao Urinar",
    "Fadiga",
    "Ganho de Peso",
    "Ansiedade",
    "Mãos e Pés Frios",
    "Mudanças de Humor",
    "Perda de Peso",
    "Inquietação",
    "Letargia",
    "Manchas na Garganta",
    "Nível Irregular de Açúcar",
    "Tosse",
    "Febre Alta",
    "Olhos Fundos",
    "Falta de Ar",
    "Suor",
    "Desidratação",
    "Indigestão",
    "Dor de Cabeça",
    "Pele Amarelada",
    "Urina Escura",
    "Náusea",
    "Perda de Apetite",
    "Dor Atrás dos Olhos",
    "Dor nas Costas",
    "Constipação",
    "Dor Abdominal",
    "Diarreia",
    "Febre Leve",
    "Urina Amarela",
    "Amarelamento dos Olhos",
    "Insuficiência Hepática Aguda",
    "Sobrecarga de Fluidos",
    "Inchaço do Estômago",
    "Linfonodos Inchados",
    "Mal-estar",
    "Visão Turva e Distorcida",
    "Catarro",
    "Irritação na Garganta",
    "Vermelhidão dos Olhos",
    "Pressão Sinusal",
    "Coriza",
    "Congestão",
    "Dor no Peito",
    "Fraqueza nos Membros",
    "Frequência Cardíaca Acelerada",
    "Dor Durante as Evacuações",
    "Dor na Região Anal",
    "Fezes com Sangue",
    "Irritação no Ânus",
    "Dor no Pescoço",
    "Tontura",
    "Cólicas",
    "Hematomas",
    "Obesidade",
    "Pernas Inchadas",
    "Vasos Sanguíneos Inchados",
    "Rosto e Olhos Inchados",
    "Tireoide Aumentada",
    "Unhas Quebradiças",
    "Extremidades Inchadas",
    "Fome Excessiva",
    "Contatos Extraconjugais",
    "Lábios Ressecados e Formigantes",
    "Fala Arrastada",
    "Dor no Joelho",
    "Dor na Articulação do Quadril",
    "Fraqueza Muscular",
    "Pescoço Rígido",
    "Articulações Inchadas",
    "Rigidez de Movimento",
    "Movimentos Giratórios",
    "Perda de Equilíbrio",
    "Instabilidade",
    "Fraqueza de um Lado do Corpo",
    "Perda do Olfato",
    "Desconforto na Bexiga",
    "Cheiro Fétido de Urina",
    "Sensação Contínua de Urina",
    "Passagem de Gases",
    "Coceira Interna",
    "Aparência Tóxica (Tifo)",
    "Depressão",
    "Irritabilidade",
    "Dor Muscular",
    "Sensório Alterado",
    "Manchas Vermelhas pelo Corpo",
    "Dor na Barriga",
    "Menstruação Anormal",
    "Manchas Discromicas",
    "Olhos Lacrimejantes",
    "Aumento do Apetite",
    "Poliúria",
    "Histórico Familiar",
    "Escarro Mucoide",
    "Escarro Enferrujado",
    "Falta de Concentração",
    "Distúrbios Visuais",
    "Recebendo Transfusão de Sangue",
    "Recebendo Injeções Não Esterilizadas",
    "Coma",
    "Sangramento Estomacal",
    "Distensão do Abdômen",
    "Histórico de Consumo de Álcool",
    "Sangue no Escarro",
    "Veias Proeminentes na Panturrilha",
    "Palpitações",
    "Caminhada Dolorosa",
    "Espinhas Cheias de Pus",
    "Cravos",
    "Escorrimento",
    "Descamação da Pele",
    "Poeira Prateada",
    "Pequenos Amassados nas Unhas",
    "Unhas Inflamatórias",
    "Bolha",
    "Ferida Vermelha ao Redor do Nariz",
    "Exsudação de Crosta Amarela",*/
  ];